const JWT_USER_PASSWORD = process.env.JWT_USER_PASSWORD;
const JWT_ADMIN_PASSWORD = process.env.JWT_ADMIN_PASSWORD;
const CONNECT_STRING = process.env.CONNECT_STRING;

module.exports = {JWT_ADMIN_PASSWORD,JWT_USER_PASSWORD,CONNECT_STRING}
